# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # CentOS 7
  BOX = "centos/7"

  # create test node
  config.vm.define :test do |test|
    test.vm.box = "#{BOX}"

    # the hostname the machine should have
    test.vm.hostname = "test"

    # time in seconds that Vagrant will wait for the machine to boot
    test.vm.boot_timeout = 300
    # disable automatic box update checking
    test.vm.box_check_update = false

    # NFS requires a host-only network to be created
    test.vm.network :private_network, ip: "10.0.20.10"

    test.vm.synced_folder "../", "/vagrant/ansible-role-sonarqube", type: "nfs"

    test.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    test.vm.provision :shell, :inline => "sudo rpm -iUvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    test.vm.provision :shell, :inline => "sudo yum update -y"
    test.vm.provision :shell, :inline => "sudo yum install -y ansible"
  end
end
